### ISSUE TITLE
Sentry_SDK: really required? [dev-music branch]

### ISSUE THREAD

**Issue by jmmelko** [e-a-h/That-Sky-Bot#30]
Hi Alex,

is sentry_sdk really necessary? 

I am asking because I need the dev-music branch to test the music cog but I get an import error with this module. Maybe could you do an optional import?

**Comment by e-a-h** [comment]
what kind of error? If you install requirements it should run fine. currently it's optionally initialized. if you don't have a SENTRY_DSN in your config.json, then sentry won't init. Ping me in the skybot discord with debugging maybe and I can try to help.

**Comment by jmmelko** [comment]
Sorry, I thought it was a dev branch specific import, also because it bears the suffix SDK, but I see it is also in the master branch and in the list requirements.txt
