### ISSUE TITLE
Put the Music Cog into production

### ISSUE THREAD

**Issue by jmmelko** [e-a-h/That-Sky-Bot#32]
- [x] solve the case where a second action asynchronously is sent to the user even though the preceding async one hasn’t been sent to the channel yet (and thus not even answered to)
- [x] wrap heavy duty functions in an executor (mainly: rendering of PNGs)
- [x] Abort the song_creation if a reaction is raised => help from Alex wanted
- [x] delete the `!song` command from public channel
- [x] maybe use reactions (numbered emojis) to answer QueryChoice (warning: would not work well with numbers > 9, revert back to text answer in this rare case?)
- [x] optional: change the locale by reacting to a flag emoji reaction? In this case, avoid resetting the questions by using maker.set_locale(locale). => would require a dictionary mapping each country to a unicode number, unless Alex or the discord servers have something ready for that

Alex TODOs:
- [x] test the Cog, and make sure that the code does not halt the bot completely because of synchronous functions (like caught in a loop), or anything dangerous due to my lack of knowledge of asyncio => Alex
- [x] add localization (structure done, just have to wait for Alex to sort things out in dev-localization)
- [x] Get ready for production: add bot metrics methods, bug reporting, logging, etc => Alex

**Comment by e-a-h** [comment]
If we should expect render times of more than a couple seconds, then also look into setting process priority as low as possible.

Definitely set a timeout for excessive render times (I don't know what to expect so will not suggest a time yet).

For user input to send signals to the process, I'd suggest doing that as a reaction in discord. See cogs/Welcomer.py `on_raw_reaction_add` for an example.

**Comment by jmmelko** [comment]
> For user input to send signals to the process, I'd suggest doing that as a reaction in discord. See cogs/Welcomer.py `on_raw_reaction_add` for an example.

Why not simply: ` async def on_message`?
It looks like it’s more restrictive, but all I want to catch is an “abort“ keyword (“cancel”, “stop”, “abort”, “quit”) in a message. 
Or are there other types of User reactions I can catch?

**Comment by e-a-h** [comment]
I suggest reaction because listening for a specific message means all kinds of possible user error. if they don't type it as you expect, they get no response and get confused. A reaction is a simple event and easy to direct people to.

**Comment by jmmelko** [comment]
I was trying to understand Discord reactions and I found this example in bugs.py:
    
            await Questions.ask(self.bot, channel, user, Lang.get_string("bugs/question_ready"),
                                [
                                    Questions.Option("YES", "Press this reaction to answer YES and begin a report"),
                                    Questions.Option("NO", "Press this reaction to answer NO", handler=abort),
                                ], show_embed=True)

the only problem is that it says that my emoji argument is None, and I did not found where it was set in the first place

**Comment by e-a-h** [comment]
I must be misunderstanding how you want to integrate "abort" into the workflow. Can you describe or graph the flow? Is "abort" something that you want available at every step, or only at specific steps? Once I understand better, I can give more coherent suggestions.

**Comment by jmmelko** [comment]
Sorry no, you’re first suggestion is the right one: I want the abort be available at every question.
It’s just that I found this simple Questions.ask example using a reaction to trigger an abort function and I thought it was simpler to test reactions because I don’t know much about discord py.
But on the end I will use an event catcher and not a question.

**Comment by e-a-h** [comment]
The approach with the bug reporting tool is that "ABORT" is only explicitly done if someone attempts to start a new report.  I think this is the safest. If you create the task and a cleanup timer for it, then member can abandon creation (close DM) and no user-initiated abort is needed. If someone abandons their submission midway and attempts to start a new one before the cleanup timer cancels the task, then you can prompt if they want to abort the existing input to start a new one, or keep the old one active.

**Comment by t1-tracey** [comment]
I did take the abort() function from the bug report cog:

https://github.com/e-a-h/That-Sky-Bot/blob/05db2dbf4f304ca838da9e0e8f4c107632739606/cogs/Music.py#L157

And yeah the abort function is called in that handler
https://github.com/e-a-h/That-Sky-Bot/blob/05db2dbf4f304ca838da9e0e8f4c107632739606/cogs/Bugs.py#L345

Hmm JMM I think the emojis appear to be called by name, list of available emojis are here:

https://github.com/e-a-h/That-Sky-Bot/blob/dev-music/utils/Emoji.py
(They can be overridden in `config.json`)

**Comment by t1-tracey** [comment]
Actually maybe we can use reactions when asking for which key, which input mode:

![Screenshot of DM with thatskymusic](https://user-images.githubusercontent.com/22441348/79082415-23918980-7d69-11ea-943c-e830b4109429.jpeg)

And another TODO, the initial `!song` command also still needs to be deleted from the channel:

![IMG_3562](https://user-images.githubusercontent.com/22441348/79082430-3f952b00-7d69-11ea-8a81-d9e5c9b43a5a.jpeg)

**Comment by jmmelko** [comment]
Yes, we could use numbers reactions for QueryChoice, but in this case we have to make sure the abort procedure is not raised upon these reactions.
Would be more difficult to do with QueryMultipleChoice, but fortunately there is none planned yet.

**Comment by jmmelko** [comment]
@e-a-h : do you know if discordpy can get the User/Member locale? Or is it private information?

**Comment by t1-tracey** [comment]
Ooh I found this in the Discord py docs `discord.ClientUser.locale`
https://discordpy.readthedocs.io/en/latest/search.html?q=Locale&check_keywords=yes&area=default

**Comment by t1-tracey** [comment]
Oh yeah we can do it for QueryChoice, and it won’t call the abort procedure:

this only calls the abort procedure for "NO" because the handler is set to the abort function 
```
await Questions.ask(self.bot, channel, user, Lang.get_string("bugs/question_ready"),
[
 Questions.Option("YES", "Press this reaction to answer YES and begin a report"),
 Questions.Option("NO", "Press this reaction to answer NO", handler=abort),
                            ], show_embed=True)

```

**Comment by e-a-h** [comment]
client locale won't be good enough for this. The way locales will be handled is like this, in order of precedence:
* default locale (en_us)
* command-trigger-specific locale override
* channel-specific locale override (ja_jp)
So channel override will always win. Trigger (like command name in japanese) will override default language in non-override channels, and otherwise default language will be used.

**Comment by e-a-h** [comment]
p.s. for locale, I want to do my best to keep language switching isolated so the `Lang.get_string` calls can stay as they are. Hopefully I can either leave the signature for get_string alone, or just add a context to the signature so no additional code will be required in any of the cogs to detect/set language.

**Comment by t1-tracey** [comment]
We have French and Vietnamese translations (funnily, the Viet translations weren’t even by me, they were contributed to the sky-python-music-sheet-maker by another player :D )

![Viet music cog](https://user-images.githubusercontent.com/22441348/79086743-86424f80-7d80-11ea-95c9-712cb87f9646.png)

so what I understand from what you’re saying, if we wanted to support those, it would be done via specific commands for that language right? I think that works (we have en_US for the default song command)

**Comment by jmmelko** [comment]
@AEnterprise, @e-a-h: should you tell otherwise, I could wrap *every* sync function of MusicMaker in an asyncio executor...
Or is there an execution time threshold below which wrapping takes more time than the mere execution of the sync task itself?

Thank you.
