### ISSUE TITLE
Music Cog: send POST request to sky-music.herokuapp.com

### ISSUE THREAD

**Issue by jmmelko** [e-a-h/That-Sky-Bot#52]
If the player wishes, an external HTTP request with POST method and JSON as data should be sent to https://sky-music.herokuapp.com/api/generateTempSong

I don’t know if I can do that just by embedding an hyperlink in the message or if I should add a YES/NO reaction and trigger a python function to do that.

**Comment by e-a-h** [comment]
I think adding the link automatically would be nice. then there's no additional work for users, and I believe usage is low enough that it won't be a bottleneck

**Comment by Specy-wot** [comment]
@jmmelko how would that reveal the API key?

**Comment by e-a-h** [comment]
in other words, use the API of sky-music app automatically when a song is generated, then show the resulting link, not the link to *create* the link

**Comment by jmmelko** [comment]
Done. Waiting for Alex to tell me how will be stored the API key.
